name: 'Auto Increment Version'
description: 'Auto Increment Version'
inputs:
  filepath:
    description: 'version properties file name'
    required: true
    default: ""
  major:
    description: 'Major version in version name'
    required: true
    default: false
  minor:
    description: 'Minor version in version name'
    required: true
    default: false
  patch:
    description: 'Patch version in version name'
    required: true
    default: true
  versioncode:
    description: 'Version Code to set'
    required: true
    default: 1
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: chmod +x ${{ github.action_path }}/autoincrement.sh
      shell: bash
    - run: autoincrement.sh ${{github.workspace}}/app/${{inputs.filepath}} ${{inputs.major}} ${{inputs.minor}} ${{inputs.patch}} ${{inputs.versioncode}}
      shell: bash
