name: 'Auto Increment Version'
description: 'Auto Increment Version'
inputs:
  filepath:
    description: 'version properties file name'
    required: true
    default: ""
  major:
    description: 'Major version in version name'
    required: true
    default: false
  minor:
    description: 'Minor version in version name'
    required: true
    default: false
  patch:
    description: 'Patch version in version name'
    required: true
    default: true
  versioncode:
    description: 'Version Code to set'
    required: true
    default: 1
runs:
  using: "composite"
  steps:
    - run: ls -al
      shell: bash
    - run: ls ${{github.action_path}}
      shell: bash
    - run: ls ${{github.workspace}}/app
      shell: bash
    - run: echo ${{inputs.filepath}}, ${{inputs.major}}, ${{inputs.minor}}, ${{inputs.patch}}, ${{inputs.versioncode}}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: chmod +x ${{ github.action_path }}/autoincrement.sh
      shell: bash
    - run: autoincrement.sh ${{github.workspace}}/app/${{inputs.filepath}} ${{inputs.major}} ${{inputs.minor}} ${{inputs.patch}} ${{inputs.versioncode}}
      shell: bash
    #- run: bash ${{github.action_path}}/autoincrement.sh ${{github.event.inputs.filepath}} ${{github.event.inputs.major}} ${{github.event.inputs.minor}} ${{github.event.inputs.patch}}
    #  shell: bash