name: 'Auto Increment Version'
description: 'Auto Increment Version'
inputs:
  filepath:
    description: 'version.properties file path'
    required: true
    default: ""
  major:
    description: 'Major version in version name'
    required: true
    default: false
  minor:
    description: 'Minor version in version name'
    required: true
    default: false
  patch:
    description: 'Patch version in version name'
    required: true
    default: true
  versioncode:
    description: 'Version Code to set'
    required: true
    default: 1
runs:
  using: "composite"
  steps:
    - run: ls -al
      shell: bash
    - run: ls .github/ -al
      shell: bash
    - run: find . -name '*autoincrement*'
      shell: bash
    - run: chmod +x autoincrement
      shell: bash
    - run: ./autoincrement ${{github.event.inputs.filepath}} ${{github.event.inputs.major}} ${{github.event.inputs.minor}} ${{github.event.inputs.patch}}
      shell: bash