#!/bin/sh

echo 'Auto Increment version'

#"./version.properties"
#MINOR=1
#MAJOR=1
#PATCH=1
#VERSION_CODE=1
#VERSION_NAME=1.1.1

file=$1

MAJOR_VERSION="1"
MINOR_VERSION="1"
PATCH_VERSION="1"
BUMP_MAJOR=false
BUMP_MINOR=false
BUMP_PATCH=true

while IFS='=' read -r key value;
do
  if [ "$key" == 'MAJOR' ]; then
    MAJOR_VERSION=$value
  elif [ "$key" == 'MINOR' ]; then
    MINOR_VERSION=$value
  elif [ "$key" == 'PATCH' ]; then
    PATCH_VERSION=$value
  fi
done <"$file"

if $BUMP_MAJOR; then NEW_MAJOR_VERSION=$((MAJOR_VERSION+1))
else NEW_MAJOR_VERSION=$MAJOR_VERSION
fi

if $BUMP_MINOR; then NEW_MINOR_VERSION=$((MINOR_VERSION+1))
else NEW_MINOR_VERSION=$MINOR_VERSION
fi

if $BUMP_PATCH; then NEW_PATCH_VERSION=$((PATCH_VERSION+1))
else NEW_PATCH_VERSION=$PATCH_VERSION
fi

SEARCH="VERSION_NAME=${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
REPLACE="VERSION_NAME=${NEW_MAJOR_VERSION}.${NEW_MINOR_VERSION}.${NEW_PATCH_VERSION}"
echo "$REPLACE"

#Replace major
sed -i '' -e "s/MAJOR=$MAJOR_VERSION/MAJOR=$NEW_MAJOR_VERSION/gi" $file
#Replace minor
sed -i '' -e "s/MINOR=$MINOR_VERSION/MINOR=$NEW_MINOR_VERSION/gi" $file
#Replace patch
sed -i '' -e "s/PATCH=$PATCH_VERSION/PATCH=$NEW_PATCH_VERSION/gi" $file
#Replace version name
sed -i '' -e "s/$SEARCH/$REPLACE/gi" $file
